services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - APP_PORT=${SERVER_PORT}
      - APP_ENV=${SERVER_ENV}
    volumes:
      - ./server:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitness_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # migrate:
  #   image: migrate/migrate
  #   volumes:
  #     - ./db/migrations:/migrations
  #   entrypoint: [
  #     "migrate",
  #     "-path=/migrations",
  #     "-database=postgres://postgres:password@db:5432/fitness_app?sslmode=disable"
  #   ]
  #   command: ["up"]
  #   depends_on:
  #     - db

volumes:
  postgres_data:
