// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AcceptFriendshipRequest struct {
	FriendshipID string `json:"friendshipID"`
}

type AddSetLog struct {
	WorkoutLogID  string   `json:"workoutLogID"`
	WorkoutTypeID string   `json:"workoutTypeID"`
	Weight        *float64 `json:"weight,omitempty"`
	RepCount      *int32   `json:"repCount,omitempty"`
	SetNumber     *int32   `json:"setNumber,omitempty"`
}

type CreateProfile struct {
	Name          string         `json:"name"`
	BirthDate     string         `json:"birthDate"`
	Gender        Gender         `json:"gender"`
	Height        *float64       `json:"height,omitempty"`
	Weight        *float64       `json:"weight,omitempty"`
	ActivityLevel *ActivityLevel `json:"activityLevel,omitempty"`
	ImageURL      *string        `json:"imageURL,omitempty"`
}

type DeleteUser struct {
	ID string `json:"id"`
}

type Friendship struct {
	ID          string           `json:"id"`
	Requester   *User            `json:"requester"`
	Requestee   *User            `json:"requestee"`
	RequesterID string           `json:"requesterID"`
	RequesteeID string           `json:"requesteeID"`
	Status      FriendshipStatus `json:"status"`
}

type Mutation struct {
}

type NewUser struct {
	Name string `json:"name"`
}

type Profile struct {
	ID            string         `json:"id"`
	User          *User          `json:"user"`
	Name          string         `json:"name"`
	BirthDate     *string        `json:"birthDate,omitempty"`
	Gender        *Gender        `json:"gender,omitempty"`
	Height        *float64       `json:"height,omitempty"`
	Weight        *float64       `json:"weight,omitempty"`
	ActivityLevel *ActivityLevel `json:"activityLevel,omitempty"`
	ImageURL      *string        `json:"imageURL,omitempty"`
	CreatedAt     string         `json:"createdAt"`
	UpdatedAt     string         `json:"updatedAt"`
}

type Query struct {
}

type RejectFriendshipRequest struct {
	FriendshipID string `json:"friendshipID"`
}

type SendFriendshipRequest struct {
	RequesteeID string `json:"requesteeID"`
}

type SetLog struct {
	ID            string       `json:"id"`
	WorkoutLog    *WorkoutLog  `json:"workoutLog"`
	WorkoutType   *WorkoutType `json:"workoutType"`
	WorkoutTypeID string       `json:"workoutTypeID"`
	Weight        int32        `json:"weight"`
	RepCount      int32        `json:"repCount"`
	SetNumber     int32        `json:"setNumber"`
}

type UpdateProfile struct {
	Name          *string        `json:"name,omitempty"`
	BirthDate     *string        `json:"birthDate,omitempty"`
	Gender        *Gender        `json:"gender,omitempty"`
	Height        *float64       `json:"height,omitempty"`
	Weight        *float64       `json:"weight,omitempty"`
	ActivityLevel *ActivityLevel `json:"activityLevel,omitempty"`
	ImageURL      *string        `json:"imageURL,omitempty"`
}

type User struct {
	ID                 string        `json:"id"`
	UID                string        `json:"uid"`
	CreatedAt          string        `json:"createdAt"`
	UpdatedAt          string        `json:"updatedAt"`
	Profile            *Profile      `json:"profile,omitempty"`
	WorkoutLogs        []*WorkoutLog `json:"workoutLogs"`
	Friends            []*User       `json:"friends"`
	FriendshipRequests []*Friendship `json:"friendshipRequests"`
	RecommendedUsers   []*User       `json:"recommendedUsers"`
}

type WorkoutLog struct {
	ID        string    `json:"id"`
	CreatedAt string    `json:"createdAt"`
	UpdatedAt string    `json:"updatedAt"`
	SetLogs   []*SetLog `json:"setLogs"`
}

type WorkoutType struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	Category    *string   `json:"category,omitempty"`
	SetLogs     []*SetLog `json:"setLogs"`
}
