// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteUser struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type NewUser struct {
	Name string `json:"name"`
}

type Query struct {
}

type User struct {
	ID        string `json:"id"`
	UID       string `json:"uid"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
