// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProfile struct {
	Name          string         `json:"name"`
	BirthDate     string         `json:"birthDate"`
	Gender        Gender         `json:"gender"`
	Height        *float64       `json:"height,omitempty"`
	Weight        *float64       `json:"weight,omitempty"`
	ActivityLevel *ActivityLevel `json:"activityLevel,omitempty"`
	ImageURL      *string        `json:"imageURL,omitempty"`
}

type DeleteUser struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type NewUser struct {
	Name string `json:"name"`
}

type Profile struct {
	ID            string         `json:"id"`
	User          *User          `json:"user"`
	Name          string         `json:"name"`
	BirthDate     *string        `json:"birthDate,omitempty"`
	Gender        *Gender        `json:"gender,omitempty"`
	Height        *float64       `json:"height,omitempty"`
	Weight        *float64       `json:"weight,omitempty"`
	ActivityLevel *ActivityLevel `json:"activityLevel,omitempty"`
	ImageURL      *string        `json:"imageURL,omitempty"`
	CreatedAt     string         `json:"createdAt"`
	UpdatedAt     string         `json:"updatedAt"`
}

type Query struct {
}

type UpdateProfile struct {
	Name          *string        `json:"name,omitempty"`
	BirthDate     *string        `json:"birthDate,omitempty"`
	Gender        *Gender        `json:"gender,omitempty"`
	Height        *float64       `json:"height,omitempty"`
	Weight        *float64       `json:"weight,omitempty"`
	ActivityLevel *ActivityLevel `json:"activityLevel,omitempty"`
	ImageURL      *string        `json:"imageURL,omitempty"`
}

type User struct {
	ID        string   `json:"id"`
	UID       string   `json:"uid"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
	Profile   *Profile `json:"profile,omitempty"`
}
