substitutions:
  _PROJECT_ID: $PROJECT_ID
  _REGION: asia-northeast1
  _REPO_API: fitness-api
  _REPO_MIGRATE: fitness-api-migrate
  _REPO_SEED: fitness-api-seed
  _JOB_NAME_MIGRATE: fitness-api-migrate
  _JOB_NAME_SEED: fitness-api-seed

steps:
  # migrate
  - id: build-migrate
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["-"]
    args: [
      'build',
      '-f', 'server/Dockerfile.migrate',
      '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_MIGRATE/fitness-api-migrate:latest',
      'server'
    ]
  - id: push-migrate
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["build-migrate"]
    args: [
      'push', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_MIGRATE/fitness-api-migrate:latest'
    ]
  - id: update-migrate-job
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: ["push-migrate"]
    entrypoint: bash
    args:
      - -c
      - >
        gcloud run jobs update $_JOB_NAME_MIGRATE \
          --image=$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_MIGRATE/fitness-api-migrate:latest \
          --region=$_REGION \
          --quiet
  - id: run-migrate-job
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: ["update-migrate-job"]
    entrypoint: gcloud
    args:
      - run
      - jobs
      - execute
      - $_JOB_NAME_MIGRATE
      - --region=$_REGION
      - --wait

  # seed
  - id: build-seed
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["-"]
    args: [
      'build',
      '-f', 'server/Dockerfile.seed',
      '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_SEED/fitness-api-seed:latest',
      'server'
    ]
  - id: push-seed
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["build-seed"]
    args: [
      'push', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_SEED/fitness-api-seed:latest'
    ]
  - id: update-seed-job
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: ["push-seed"]
    entrypoint: bash
    args:
      - -c
      - >
        gcloud run jobs update $_JOB_NAME_SEED \
          --image=$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_SEED/fitness-api-seed:latest \
          --region=$_REGION \
          --quiet

  # api
  - id: build-api
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["-"]
    args: [
      'build',
      '-f', 'server/Dockerfile',
      '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_API/fitness-api:latest',
      'server'
    ]
  - id: push-api
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ["build-api"]
    args: [
      'push', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_API/fitness-api:latest'
    ]
  - id: deploy-api
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: ["push-api","run-migrate"]
    entrypoint: gcloud
    args:
      - run
      - deploy
      - fitness-api
      - --region=$_REGION
      - --image=$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO_API/fitness-api:latest
      - --quiet

options:
  logging: CLOUD_LOGGING_ONLY
