name: CI(server)

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-diff:
    runs-on: ubuntu-latest
    outputs:
      has-changed-files: ${{ steps.check-files.outputs.any_changed == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check files
        id: check-files
        uses: tj-actions/changed-files@v40
        with:
          files: "server/**"
  build:
    runs-on: ubuntu-latest
    needs: check-diff
    if: needs.check-diff.outputs.has-changed-files == 'true'
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.5
      - name: Install dependencies
        run: go mod tidy