name: CI(client)

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-diff:
    runs-on: ubuntu-latest
    outputs:
      has-changed-files: ${{ steps.check-files.outputs.any_changed == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check files
        id: check-files
        uses: tj-actions/changed-files@v40
        with:
          files: "client/**"
  build:
    runs-on: ubuntu-latest
    needs: check-diff
    if: needs.check-diff.outputs.has-changed-files == 'true'
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Remove package-lock.json
        run: rm -f package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint